all:
  hosts:
    control-plane-1:
      ansible_host: 10.0.1.24
      ip: 10.0.1.24
      access_ip: 10.0.1.24
    worker-1:
      ansible_host: 10.0.1.10
      ip: 10.0.1.10
      access_ip: 10.0.1.10
    worker-2:
      ansible_host: 10.0.2.8
      ip: 10.0.2.8
      access_ip: 10.0.2.8
    cl1u5i3na4qn8r3bfhtu-upub:
      ansible_host: 10.0.1.35
      ip: 10.0.1.35
      access_ip: 10.0.1.35
  children:
    kube_control_plane:
      hosts:
        control-plane-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        control-plane-1:
    kube-ingress:
      hosts:
        cl1u5i3na4qn8r3bfhtu-upub:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
