all:
  hosts:
    control-plane-1:
      ansible_host:10.0.1.10
      ip:10.0.1.10
      access_ip:10.0.1.10  
    worker-1:
      ansible_host:10.0.1.32
      ip:10.0.1.32
      access_ip:10.0.1.32
    worker-2:
      ansible_host:10.0.2.7
      ip:10.0.2.7
      access_ip:10.0.2.7
  children:
    kube_control_plane:
      hosts:
        control-plane-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        control-plane-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
