# deploy_kubespray:
#   stage: install k8s-cluster with kubespray
#   variables:
#     ANSIBLE_CONFIG: "kubernetes/ansible.cfg"
#   image: cr.yandex/crpb6jem7gml01esa824/ansible-dind:0.1
#   before_script:
#     - cp compute_instance/hosts.yaml kubernetes/mycluster
#     - cat compute_instance/k8s-cluster.yaml | sed 's/$/\n/' | sed '/^$/d' >> kubernetes/mycluster/group_vars/k8s_cluster/k8s-cluster.yml
#     - cd kubernetes
#     - git clone https://github.com/kubernetes-sigs/kubespray.git 
#     - cp -r mycluster kubespray/inventory
#     - cd kubespray
#   script:
#     - cat inventory/mycluster/hosts.yaml
#     - cat inventory/mycluster/group_vars/k8s_cluster/addons.yml
#     - cat inventory/mycluster/group_vars/k8s_cluster/k8s-cluster.yml
#     - ansible-playbook -i inventory/mycluster/hosts.yaml cluster.yml -b
#   # when: manual
#   needs:
#     - apply_compute_instance
#   tags:
#     - docker

scrape_kubeconfig:
  stage: install k8s-cluster with kubespray
  image: cr.yandex/crpb6jem7gml01esa824/ansible-dind:0.1
  before_script:
    - export IP_CONTROL_PLANE=$(cat compute_instance/ip_control_plane.cfg) 
    - echo $IP_CONTROL_PLANE
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p ~/.kube
    - ssh -o StrictHostKeyChecking=no -i /opt/kubespray/vm ubuntu@$IP_CONTROL_PLANE 'sudo cat /etc/kubernetes/admin.conf' > ~/.kube/config
    - kubectl config set-cluster cluster.local --server=https://$IP_CONTROL_PLANE:6443
  script:
    - kubectl get pod
  tags:
    - docker
  needs:
    - apply_compute_instance
    # - deploy_kubespray